"use client";

import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, Ban, BriefcaseBusiness, CircleDollarSign, Eye, Search, ShieldCheck, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";

export type AdminTab = "overview" | "moderation" | "users" | "projects" | "billing";

export function AdminClient({ name, demo=false, initialTab="overview" }: {name:string;demo?:boolean;initialTab?:AdminTab}) {
  const router=useRouter();const tab=initialTab;function changeTab(next:AdminTab){router.replace(`/admin?tab=${next}${demo?"&demo=1":""}`,{scroll:false})}
  return <AppShell role="admin" name={name}><div className="mx-auto max-w-[1360px]">{demo && <div className="mb-5 rounded-xl border border-[#f0d998] bg-[#fff7dc] p-4 text-sm text-[#725815]"><strong>Admin preview:</strong> seeded operational data is shown until an authorised admin signs in.</div>}<div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="eyebrow">Marketplace operations</p><h1 className="mt-2 text-4xl font-black tracking-[-.045em]">Admin overview</h1><p className="mt-2 text-[#62708a]">Health, moderation, users, projects, and billing in one workspace.</p></div><div className="flex max-w-full gap-1 overflow-auto rounded-xl border border-[#dce4ef] bg-white p-1.5">{(["overview","moderation","users","projects","billing"] as AdminTab[]).map(item=><button key={item} onClick={()=>changeTab(item)} className={`rounded-lg px-4 py-2 text-sm font-extrabold capitalize ${tab===item?"bg-[#0b68ed] text-white":"text-[#62708a] hover:bg-[#eef4fb]"}`}>{item}</button>)}</div></div><div className="mt-8">{tab==="overview"&&<Overview/>}{tab==="moderation"&&<Moderation/>}{tab==="users"&&<Users/>}{tab==="projects"&&<Projects/>}{tab==="billing"&&<Billing/>}</div></div></AppShell>;
}

function Overview(){return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminStat label="Total users" value="2,846" trend="+8.2%" up icon={<UsersRound/>}/><AdminStat label="Open projects" value="418" trend="+12.4%" up icon={<BriefcaseBusiness/>}/><AdminStat label="Paid members" value="732" trend="+5.7%" up icon={<CircleDollarSign/>}/><AdminStat label="Open reports" value="14" trend="-18.0%" icon={<AlertTriangle/>}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><section className="card p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Marketplace activity</h2><p className="mt-1 text-sm text-[#73809a]">Projects and quotes in the last seven days</p></div><span className="status-pill bg-[#e9f8f1] text-[#0d8154]">Healthy</span></div><div className="mt-9 flex h-[240px] items-end gap-3 border-b border-[#dfe6f0] pl-2">{[45,72,58,88,67,95,82].map((n,i)=><div key={i} className="flex h-full flex-1 items-end gap-1"><div style={{height:`${n}%`}} className="w-1/2 rounded-t bg-[#0b68ed]"/><div style={{height:`${Math.max(n-24,22)}%`}} className="w-1/2 rounded-t bg-[#bcd7fa]"/></div>)}</div><div className="mt-4 flex items-center gap-5 text-xs font-bold text-[#6e7b91]"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-[#0b68ed]"/>Projects</span><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-[#bcd7fa]"/>Quotes</span></div></section><section className="card p-6"><h2 className="text-xl font-black">Action queue</h2><p className="mt-1 text-sm text-[#73809a]">Items that need a human decision</p><div className="mt-6 grid gap-4"><Queue count="7" label="User reports" tone="red"/><Queue count="4" label="Profiles awaiting verification" tone="yellow"/><Queue count="3" label="Disputed credit charges" tone="blue"/><Queue count="12" label="Flagged project descriptions" tone="gray"/></div></section></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><RecentUsers/><RecentProjects/></div></>}
function Moderation(){return <section id="moderation" className="card overflow-hidden"><TableHeading title="Moderation queue" subtitle="Review reports and content signals before taking action."/><div className="divide-y divide-[#e7ecf3]">{[["Misleading qualification claim","Morgan Renovations","Profile report","High"],["Contact details posted publicly","Bathroom refresh","Project content","Medium"],["Repeated unsolicited messages","Auckland Sparkies","User conduct","High"],["Possible duplicate project","Deck rebuild","Project content","Low"]].map((r,i)=><div key={i} className="grid gap-4 p-5 lg:grid-cols-[1.5fr_1fr_1fr_.6fr_auto] lg:items-center"><div className="font-extrabold">{r[0]}</div><div className="text-sm text-[#62708a]">{r[1]}</div><div className="text-sm text-[#62708a]">{r[2]}</div><span className={`status-pill w-fit ${r[3]==="High"?"bg-[#fff0ef] text-[#cf3838]":r[3]==="Medium"?"bg-[#fff7dc] text-[#85650d]":"bg-[#eef1f5] text-[#647086]"}`}>{r[3]}</span><div className="flex gap-2"><button className="rounded-lg border border-[#dce4ef] p-2" title="Review"><Eye size={17}/></button><button className="rounded-lg border border-[#f1baba] p-2 text-[#cf3838]" title="Suspend"><Ban size={17}/></button></div></div>)}</div></section>}
function Users(){return <section id="users" className="card overflow-hidden"><TableHeading title="User management" subtitle="Search, verify, suspend, and review account history." search/><div className="divide-y divide-[#e7ecf3]">{[["Aroha King","Homeowner","Auckland","Active"],["Birch Plumbing Ltd","Tradesperson","Auckland","Verified"],["South Coast Build","Tradesperson","Wellington","Review"],["Mia Thompson","Homeowner","Christchurch","Active"],["Kai Electrical","Tradesperson","Hamilton","Suspended"]].map((u,i)=><div key={i} className="grid gap-3 p-5 sm:grid-cols-[1.5fr_1fr_1fr_.7fr_auto] sm:items-center"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#eaf3ff] font-black text-[#0b68ed]">{u[0][0]}</div><span className="font-extrabold">{u[0]}</span></div><span className="text-sm text-[#62708a]">{u[1]}</span><span className="text-sm text-[#62708a]">{u[2]}</span><span className={`status-pill w-fit ${u[3]==="Verified"?"bg-[#e9f8f1] text-[#0d8154]":u[3]==="Suspended"?"bg-[#fff0ef] text-[#cf3838]":u[3]==="Review"?"bg-[#fff7dc] text-[#85650d]":"bg-[#eef4fb] text-[#245d9f]"}`}>{u[3]}</span><button className="text-sm font-extrabold text-[#0b68ed]">Open</button></div>)}</div></section>}
function Projects(){return <section id="projects" className="card overflow-hidden"><TableHeading title="Project operations" subtitle="All marketplace listings and lifecycle states." search/><div className="divide-y divide-[#e7ecf3]">{[["Kitchen renovation","Aroha King","Builders","Open","6"],["Bathroom plumbing refresh","Mia Thompson","Plumbing","Awarded","5"],["Retaining wall","Jordan Lee","Landscaping","Open","2"],["Switchboard upgrade","Theo Martin","Electrical","Flagged","3"],["Interior repaint","Priya Shah","Painting","Completed","7"]].map((p,i)=><div key={i} className="grid gap-3 p-5 lg:grid-cols-[1.6fr_1fr_1fr_.7fr_.4fr_auto] lg:items-center"><span className="font-extrabold">{p[0]}</span><span className="text-sm text-[#62708a]">{p[1]}</span><span className="text-sm text-[#62708a]">{p[2]}</span><span className={`status-pill w-fit ${p[3]==="Flagged"?"bg-[#fff0ef] text-[#cf3838]":p[3]==="Completed"?"bg-[#e9f8f1] text-[#0d8154]":"bg-[#eaf3ff] text-[#0b68ed]"}`}>{p[3]}</span><span className="text-sm font-bold">{p[4]} quotes</span><button className="text-sm font-extrabold text-[#0b68ed]">View</button></div>)}</div></section>}
function Billing(){return <div id="billing" className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className="card p-6"><h2 className="text-xl font-black">Membership revenue</h2><p className="mt-1 text-sm text-[#73809a]">Subscription health and credit purchases</p><div className="mt-7 grid gap-4 sm:grid-cols-3"><MiniMetric label="Monthly recurring" value="$32,480"/><MiniMetric label="Credit top-ups" value="$6,220"/><MiniMetric label="Payment failures" value="9"/></div><div className="mt-8 divide-y divide-[#e7ecf3] border-y border-[#e7ecf3]">{[["Trade Pro monthly","428","$24,420"],["Starter monthly","304","$8,060"],["Credit top-up","197","$6,220"]].map(r=><div key={r[0]} className="grid grid-cols-3 py-4 text-sm"><span className="font-extrabold">{r[0]}</span><span className="text-center text-[#62708a]">{r[1]} purchases</span><span className="text-right font-black">{r[2]}</span></div>)}</div></section><aside className="card p-6"><ShieldCheck className="text-[#16a56b]" size={34}/><h2 className="mt-4 text-xl font-black">Stripe webhook health</h2><p className="mt-2 text-sm leading-6 text-[#62708a]">Last event processed 42 seconds ago. No failed events in the last 24 hours.</p><div className="mt-6 rounded-xl bg-[#e9f8f1] p-4 text-sm font-extrabold text-[#0d8154]">Operational</div><div className="mt-6 grid gap-3 text-sm"><div className="flex justify-between"><span className="text-[#62708a]">Processed today</span><strong>1,284</strong></div><div className="flex justify-between"><span className="text-[#62708a]">Retries</span><strong>3</strong></div><div className="flex justify-between"><span className="text-[#62708a]">Failed</span><strong>0</strong></div></div></aside></div>}

function AdminStat({label,value,trend,up=false,icon}:{label:string;value:string;trend:string;up?:boolean;icon:React.ReactNode}){return <div className="card p-5"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf3ff] text-[#0b68ed]">{icon}</div><span className={`flex items-center gap-1 text-xs font-extrabold ${up?"text-[#16a56b]":"text-[#d55454]"}`}>{trend}{up?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>}</span></div><div className="mt-5 text-3xl font-black">{value}</div><div className="mt-1 text-sm font-semibold text-[#73809a]">{label}</div></div>}
function Queue({count,label,tone}:{count:string;label:string;tone:string}){const colors:Record<string,string>={red:"bg-[#fff0ef] text-[#d84a4a]",yellow:"bg-[#fff7dc] text-[#85650d]",blue:"bg-[#eaf3ff] text-[#0b68ed]",gray:"bg-[#eef1f5] text-[#647086]"};return <div className="flex items-center justify-between rounded-xl border border-[#e1e7f0] p-4"><span className="text-sm font-bold">{label}</span><span className={`grid h-8 min-w-8 place-items-center rounded-lg px-2 text-sm font-black ${colors[tone]}`}>{count}</span></div>}
function TableHeading({title,subtitle,search=false}:{title:string;subtitle:string;search?:boolean}){return <div className="flex flex-col justify-between gap-4 border-b border-[#e7ecf3] p-6 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-[#73809a]">{subtitle}</p></div>{search&&<label className="flex items-center gap-2 rounded-xl border border-[#dce4ef] px-3"><Search size={17} className="text-[#73809a]"/><input className="h-10 outline-none" placeholder="Search records"/></label>}</div>}
function MiniMetric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f4f7fb] p-4"><div className="text-xs font-bold text-[#73809a]">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
function RecentUsers(){return <section className="card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">New tradespeople</h2><button className="text-sm font-extrabold text-[#0b68ed]">View users</button></div><div className="mt-5 grid gap-4">{[["North & Co.","Builders","Pending review"],["Kai Electrical","Electrical","Verified"],["Greenline Gardens","Landscaping","Profile 78%"]].map(u=><div key={u[0]} className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#eaf3ff] font-black text-[#0b68ed]">{u[0][0]}</div><div><div className="text-sm font-extrabold">{u[0]}</div><div className="text-xs text-[#73809a]">{u[1]}</div></div></div><span className="text-xs font-bold text-[#62708a]">{u[2]}</span></div>)}</div></section>}
function RecentProjects(){return <section className="card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Recent projects</h2><button className="text-sm font-extrabold text-[#0b68ed]">View projects</button></div><div className="mt-5 grid gap-4">{[["Kitchen renovation","6 quotes","Open"],["Roof leak repair","4 quotes","Urgent"],["Native garden design","2 quotes","Open"]].map(p=><div key={p[0]} className="flex items-center justify-between"><div><div className="text-sm font-extrabold">{p[0]}</div><div className="mt-1 text-xs text-[#73809a]">{p[1]}</div></div><span className={`status-pill ${p[2]==="Urgent"?"bg-[#fff0ef] text-[#cf3838]":"bg-[#e9f8f1] text-[#0d8154]"}`}>{p[2]}</span></div>)}</div></section>}
