import type Stripe from "stripe";
import { createAdminClient } from "@/lib/supabase/admin";
import { getStripeClient } from "@/lib/stripe";
import { lookupPrice } from "@/lib/plans";

export const runtime="nodejs";

async function claimEvent(event:Stripe.Event){const admin=createAdminClient();const{error}=await admin.from("stripe_webhook_events").insert({id:event.id,event_type:event.type,status:"processing"});if(!error)return true;if(error.code!=="23505")throw error;const{data:existing,error:readError}=await admin.from("stripe_webhook_events").select("status").eq("id",event.id).single();if(readError)throw readError;if(existing.status!=="failed")return false;const{error:retryError}=await admin.from("stripe_webhook_events").update({status:"processing",error:null,updated_at:new Date().toISOString()}).eq("id",event.id).eq("status","failed");if(retryError)throw retryError;return true}
async function finishEvent(id:string,status:"processed"|"failed",error?:string){await createAdminClient().from("stripe_webhook_events").update({status,error:error||null,processed_at:status==="processed"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",id)}
const objectId=(value:unknown)=>typeof value==="string"?value:value&&typeof value==="object"&&"id" in value?String(value.id):null;

async function upsertSubscription(subscription:Stripe.Subscription){const userId=subscription.metadata.user_id;if(!userId)return;const item=subscription.items.data[0];const priceId=item?.price.id;const plan=priceId?lookupPrice(priceId):null;await createAdminClient().from("subscriptions").upsert({user_id:userId,stripe_customer_id:objectId(subscription.customer),stripe_subscription_id:subscription.id,stripe_price_id:priceId||null,plan_name:plan?.kind==="subscription"?plan.plan.name:null,status:subscription.status,current_period_end:item?.current_period_end?new Date(item.current_period_end*1000).toISOString():null,cancel_at_period_end:subscription.cancel_at_period_end},{onConflict:"user_id"})}
async function creditTokens(userId:string,tokens:number,eventId:string,reason:string){const{error}=await createAdminClient().rpc("credit_tokens_for_stripe",{target_user_id:userId,token_amount:tokens,source_event_id:eventId,ledger_reason:reason});if(error)throw error}

async function processEvent(event:Stripe.Event){const stripe=getStripeClient();if(event.type==="checkout.session.completed"||event.type==="checkout.session.async_payment_succeeded"){const session=event.data.object as Stripe.Checkout.Session;if(session.mode==="payment"&&session.payment_status==="paid"){const userId=session.metadata?.user_id;const tokens=Number(session.metadata?.tokens);if(userId&&Number.isInteger(tokens)&&tokens>0)await creditTokens(userId,tokens,event.id,"stripe_credit_purchase");}if(event.type==="checkout.session.completed"&&session.mode==="subscription"){const id=objectId(session.subscription);if(id)await upsertSubscription(await stripe.subscriptions.retrieve(id));}return}if(event.type==="customer.subscription.created"||event.type==="customer.subscription.updated"||event.type==="customer.subscription.deleted"){await upsertSubscription(event.data.object as Stripe.Subscription);return}if(event.type==="invoice.payment_succeeded"){const invoice=event.data.object as Stripe.Invoice;const details=invoice.parent?.type==="subscription_details"?invoice.parent.subscription_details:null;const id=details?objectId(details.subscription):null;if(!id)return;const subscription=await stripe.subscriptions.retrieve(id);await upsertSubscription(subscription);const userId=subscription.metadata.user_id;const plan=lookupPrice(subscription.items.data[0]?.price.id||"");if(userId&&plan?.kind==="subscription")await creditTokens(userId,plan.tokens,event.id,"membership_renewal");}}

export async function POST(request:Request){const signature=request.headers.get("stripe-signature");const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!signature||!secret)return new Response("Missing webhook configuration",{status:400});let event:Stripe.Event;try{event=getStripeClient().webhooks.constructEvent(await request.text(),signature,secret)}catch{return new Response("Invalid webhook signature",{status:400})}try{if(!(await claimEvent(event)))return Response.json({received:true});await processEvent(event);await finishEvent(event.id,"processed");return Response.json({received:true})}catch(error){console.error("Stripe webhook processing failed",{eventId:event.id,eventType:event.type});await finishEvent(event.id,"failed",error instanceof Error?error.message:"Unknown error");return new Response("Webhook processing failed",{status:500})}}
