"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, ImagePlus, LoaderCircle, MapPin } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { categories as fallbackCategories, nzCities } from "@/lib/mock-data";

type Category={id:string;name:string;slug:string};

export function ProjectForm(){const router=useRouter();const[step,setStep]=useState(1);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");const[categories,setCategories]=useState<Category[]>(fallbackCategories.map(c=>({id:c.slug,name:c.name,slug:c.slug})));useEffect(()=>{fetch("/api/categories").then(response=>response.ok?response.json():[]).then((data:Category[])=>{if(data.length)setCategories(data)}).catch(()=>undefined)},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");try{const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please log in as a homeowner to publish your project.");const form=new FormData(e.currentTarget);const categoryId=String(form.get("category"));const chosen=categories.find(c=>c.id===categoryId);if(!chosen||chosen.id===chosen.slug)throw new Error("Please choose a live trade category after signing in.");const{data:project,error}=await supabase.from("projects").insert({homeowner_id:user.id,title:String(form.get("title")),city:String(form.get("city")),category_id:categoryId,description:String(form.get("description")),budget_min:Number(form.get("budgetMin"))||null,budget_max:Number(form.get("budgetMax"))||null,hire_likelihood:String(form.get("likelihood")),project_stage:String(form.get("stage")),target_date:String(form.get("targetDate"))||null,keywords:String(form.get("keywords")).split(",").map(v=>v.trim()).filter(Boolean),status:"open"}).select("id").single();if(error)throw error;const files=form.getAll("photos").filter((value):value is File=>value instanceof File&&value.size>0);for(const file of files.slice(0,8)){const signed=await fetch("/api/uploads/sign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scope:"project",referenceId:project.id,fileName:file.name,contentType:file.type,size:file.size})});const prepared=await signed.json();if(!signed.ok)throw new Error(prepared.error??"Could not prepare media upload.");const uploaded=await fetch(prepared.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type},body:file});if(!uploaded.ok)throw new Error("A project file could not be uploaded.");const{error:mediaError}=await supabase.from("project_media").insert({project_id:project.id,owner_id:user.id,storage_path:prepared.key,media_type:file.type.startsWith("video/")?"video":"image"});if(mediaError)throw mediaError;}router.push("/dashboard");router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Could not publish your project.");}finally{setLoading(false)}}
  return <form onSubmit={submit} className="grid gap-8 lg:grid-cols-[1fr_320px]"><section className="card p-6 sm:p-9"><div className="mb-8 flex items-center gap-2">{[1,2,3].map(n=><div key={n} className="flex flex-1 items-center gap-2"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-sm font-black ${step>=n?"bg-[#0b68ed] text-white":"bg-[#e9eef5] text-[#7e899c]"}`}>{step>n?<Check size={16}/>:n}</span>{n<3&&<span className={`h-1 flex-1 rounded ${step>n?"bg-[#0b68ed]":"bg-[#e9eef5]"}`}/>}</div>)}</div>
    <div className={step===1?"":"hidden"}><p className="eyebrow">Step 1 of 3</p><h2 className="mt-2 text-3xl font-black tracking-tight">What needs doing?</h2><p className="mt-2 text-sm text-[#62708a]">A clear title and project description get more useful quotes.</p><div className="mt-7 grid gap-5"><label className="grid gap-2 text-sm font-bold">Project title<input name="title" required minLength={3} maxLength={120} className="field" placeholder="e.g. Rebuild our back deck"/></label><label className="grid gap-2 text-sm font-bold">Trade category<select name="category" required className="field"><option value="">Choose a category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Project description<textarea name="description" required minLength={20} maxLength={5000} className="field" placeholder="Describe the current site, the result you want, and anything a tradesperson should know…"/></label><label className="grid gap-2 text-sm font-bold">Keywords<input name="keywords" className="field" placeholder="decking, timber, outdoor (comma separated)"/></label></div></div>
    <div className={step===2?"":"hidden"}><p className="eyebrow">Step 2 of 3</p><h2 className="mt-2 text-3xl font-black tracking-tight">Location, budget, timing.</h2><p className="mt-2 text-sm text-[#62708a]">These details help the right tradespeople decide quickly.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold sm:col-span-2">General location<div className="relative"><MapPin className="absolute left-3 top-3.5 text-[#0b68ed]" size={18}/><select name="city" required className="field pl-10"><option value="">Choose a city</option>{nzCities.map(c=><option key={c}>{c}</option>)}</select></div></label><label className="grid gap-2 text-sm font-bold">Budget from (NZD)<input name="budgetMin" min="0" step="100" type="number" className="field" placeholder="3000"/></label><label className="grid gap-2 text-sm font-bold">Budget to (NZD)<input name="budgetMax" min="0" step="100" type="number" className="field" placeholder="5000"/></label><label className="grid gap-2 text-sm font-bold">Hiring likelihood<select name="likelihood" className="field"><option value="exploring">Exploring options</option><option value="planning">Planning to hire</option><option value="ready">Ready to hire</option><option value="urgent">Urgent</option></select></label><label className="grid gap-2 text-sm font-bold">Project stage<select name="stage" className="field"><option value="planning">Planning</option><option value="consent">Consent / design</option><option value="ready">Ready to start</option><option value="in_progress">Already underway</option></select></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Preferred completion date<input name="targetDate" type="date" className="field"/></label></div></div>
    <div className={step===3?"":"hidden"}><p className="eyebrow">Step 3 of 3</p><h2 className="mt-2 text-3xl font-black tracking-tight">Show the site.</h2><p className="mt-2 text-sm text-[#62708a]">Photos help tradespeople understand access, condition, and scale before they quote.</p><label className="mt-7 grid min-h-[260px] cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-[#b8c7da] bg-[#f7f9fc] p-8 text-center transition hover:border-[#0b68ed] hover:bg-[#eef5ff]"><input type="file" name="photos" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime" multiple className="sr-only"/><span><ImagePlus className="mx-auto text-[#0b68ed]" size={42}/><strong className="mt-4 block text-lg">Add project photos or a short video</strong><span className="mt-2 block text-sm text-[#73809a]">Up to 8 files · JPG, PNG, WebP, MP4 or MOV</span></span></label><div className="mt-5 rounded-xl bg-[#fff7dc] p-4 text-sm leading-6 text-[#725815]">Avoid showing faces, number plates, or sensitive documents. Authenticated tradespeople can view project media.</div></div>
    <div className="mt-8 flex justify-between border-t border-[#e3e9f1] pt-6">{step>1?<button type="button" onClick={()=>setStep(step-1)} className="btn-outline">Back</button>:<span/>}{step<3?<button type="button" onClick={()=>setStep(step+1)} className="btn-primary">Continue <ArrowRight size={17}/></button>:<button disabled={loading} className="btn-primary">{loading?<LoaderCircle className="animate-spin" size={18}/>:<>Publish project <ArrowRight size={17}/></>}</button>}</div>{message&&<p className="mt-5 rounded-xl bg-[#fff0ef] p-4 text-sm text-[#a43d3d]">{message}</p>}</section>
    <aside className="space-y-5"><div className="rounded-2xl bg-[#071329] p-6 text-white"><h3 className="text-xl font-black">Posting is free.</h3><p className="mt-3 text-sm leading-6 text-[#a9b6cc]">You decide who to talk with and who to hire. Trade Seekerz does not award the job for you.</p><div className="mt-6 grid gap-3 text-sm font-bold"><span className="flex gap-2"><Check size={17} className="text-[#16d68c]"/>Receive multiple quotes</span><span className="flex gap-2"><Check size={17} className="text-[#16d68c]"/>Compare verified profiles</span><span className="flex gap-2"><Check size={17} className="text-[#16d68c]"/>Message securely</span></div></div><div className="card p-6"><h3 className="font-black">A better brief gets better quotes</h3><p className="mt-3 text-sm leading-6 text-[#62708a]">Mention access, measurements, existing materials, and whether plans or consent are already sorted.</p></div></aside>
  </form>}
