"use client";

import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Clock3, Coins, FileText, MapPin, MessageSquare, Plus, Star, TrendingUp, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { jobs } from "@/lib/mock-data";

export function DashboardClient({ role, name, demo=false }: { role:"homeowner"|"tradesperson"; name:string; demo?:boolean }) {
  return <AppShell role={role} name={name}>{demo && <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#b7d3fb] bg-[#eaf3ff] p-4 text-sm text-[#174982]"><span><strong>Preview mode:</strong> This is seeded interface data. Live accounts use Supabase.</span><Link href={`/dashboard?demo=${role === "homeowner" ? "tradesperson" : "homeowner"}`} className="font-extrabold text-[#0b68ed]">Switch to {role === "homeowner" ? "tradesperson" : "homeowner"} view</Link></div>}{role === "homeowner" ? <HomeownerDashboard name={name}/> : <TradespersonDashboard name={name} demo={demo}/>}</AppShell>;
}

function HomeownerDashboard({ name }: {name:string}) {
  return <div className="mx-auto max-w-[1280px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Homeowner workspace</p><h1 className="mt-2 text-4xl font-black tracking-[-.045em]">Kia ora, {name}.</h1><p className="mt-2 text-[#62708a]">Here’s what’s happening with your projects.</p></div><Link href="/projects/new" className="btn-primary"><Plus size={18}/>Post a new job</Link></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Active projects" value="3" note="1 needs a response" icon={<BriefcaseBusiness/>}/><Stat label="New quotes" value="7" note="Across 2 projects" icon={<FileText/>}/><Stat label="Unread messages" value="4" note="Latest 12 minutes ago" icon={<MessageSquare/>}/><Stat label="Tradies compared" value="11" note="This month" icon={<UsersRound/>}/></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><section id="projects" className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e2e9f2] p-6"><div><h2 className="text-xl font-black">Your projects</h2><p className="mt-1 text-sm text-[#73809a]">Quotes, messages, and progress at a glance.</p></div><button className="text-sm font-extrabold text-[#0b68ed]">View all</button></div><div className="divide-y divide-[#e8edf4]"><ProjectRow title="Kitchen renovation" meta="Mount Eden · Builders" status="6 quotes" tone="blue"/><ProjectRow title="Garden retaining wall" meta="Grey Lynn · Landscaping" status="Chatting" tone="green"/><ProjectRow title="Replace hot water cylinder" meta="Onehunga · Plumbing" status="Completed" tone="gray"/></div></section><aside className="card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Recent quotes</h2><FileText className="text-[#0b68ed]"/></div><div className="mt-6 grid gap-5"><Quote name="Birch Build Co." amount="$18,450" rating="4.9"/><Quote name="North & Co." amount="$19,100" rating="4.8"/><Quote name="Craftline" amount="$17,980" rating="4.7"/></div><button className="btn-outline mt-6 w-full">Compare all quotes</button></aside></div>
    <section className="mt-8 rounded-2xl bg-[#0b68ed] p-7 text-white sm:flex sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black">Keep the detail with the project.</h2><p className="mt-2 text-sm text-[#cfe2fd]">Messages and quotes stay connected, so decisions are easier to follow.</p></div><Link href="/messages" className="btn-yellow mt-5 sm:mt-0">Open messages <ArrowRight size={17}/></Link></section>
  </div>;
}

function TradespersonDashboard({name,demo=false}:{name:string;demo?:boolean}) {
  return <div className="mx-auto max-w-[1280px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Tradesperson workspace</p><h1 className="mt-2 text-4xl font-black tracking-[-.045em]">Morning, {name}.</h1><p className="mt-2 text-[#62708a]">Fresh work that matches your profile and service area.</p></div><Link href="/jobs" className="btn-primary">Find new work <ArrowRight size={18}/></Link></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Available credits" value="32" note="25 renew on 1 Nov" icon={<Coins/>}/><Stat label="Active leads" value="8" note="3 new today" icon={<TrendingUp/>}/><Stat label="Quotes sent" value="12" note="42% response rate" icon={<FileText/>}/><Stat label="Profile rating" value="4.9" note="38 homeowner reviews" icon={<Star/>}/></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><section id="leads" className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e2e9f2] p-6"><div><h2 className="text-xl font-black">Recommended leads</h2><p className="mt-1 text-sm text-[#73809a]">Based on your building services and Auckland area.</p></div><Link href="/jobs" className="text-sm font-extrabold text-[#0b68ed]">See all</Link></div><div className="divide-y divide-[#e8edf4]">{jobs.slice(0,4).map(job=><Link href={`/jobs/${job.id}`} key={job.id} className="group grid gap-3 p-5 transition hover:bg-[#f7faff] sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold group-hover:text-[#0b68ed]">{job.title}</h3><span className={`status-pill ${job.timing === "Urgent" ? "bg-[#fff0ef] text-[#d93f3f]" : "bg-[#e9f8f1] text-[#0d8154]"}`}>{job.timing}</span></div><div className="mt-2 flex flex-wrap gap-4 text-xs text-[#6d7b91]"><span className="flex gap-1"><MapPin size={14}/>{job.location}</span><span className="flex gap-1"><Clock3 size={14}/>{job.age}</span></div></div><div className="text-sm font-black text-[#0b1833]">{job.budget}</div></Link>)}</div></section><aside className="grid gap-6"><div className="card p-6"><div className="flex items-center gap-3"><BadgeCheck className="text-[#16a56b]"/><div><div className="font-black">Profile looking strong</div><div className="text-xs text-[#73809a]">82% complete</div></div></div><div className="mt-5 h-2 rounded-full bg-[#e8edf4]"><div className="h-full w-[82%] rounded-full bg-[#16a56b]"/></div><p className="mt-4 text-sm leading-6 text-[#62708a]">Add two recent project photos to improve homeowner response.</p><Link href={demo?"/profile/demo":"/settings"} className="mt-4 inline-flex text-sm font-extrabold text-[#0b68ed]">Finish profile →</Link></div><div className="rounded-2xl bg-[#071329] p-6 text-white"><Coins/><h2 className="mt-4 text-xl font-black">Need more credits?</h2><p className="mt-2 text-sm leading-6 text-[#a9b6cc]">Top up any time or switch plan as your pipeline grows.</p><Link href="/pricing" className="btn-yellow mt-5 w-full">View billing</Link></div></aside></div>
  </div>;
}

function Stat({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}) { return <div className="card p-5"><div className="flex items-start justify-between"><span className="text-sm font-bold text-[#6b7890]">{label}</span><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf3ff] text-[#0b68ed]">{icon}</span></div><div className="mt-4 text-3xl font-black tracking-tight">{value}</div><div className="mt-2 text-xs font-semibold text-[#8692a7]">{note}</div></div>; }
function ProjectRow({title,meta,status,tone}:{title:string;meta:string;status:string;tone:"blue"|"green"|"gray"}) { const colors={blue:"bg-[#eaf3ff] text-[#0b68ed]",green:"bg-[#e9f8f1] text-[#0d8154]",gray:"bg-[#eef1f5] text-[#5e6b80]"}; return <div className="flex flex-col justify-between gap-3 p-5 sm:flex-row sm:items-center"><div><h3 className="font-extrabold">{title}</h3><p className="mt-1 text-sm text-[#73809a]">{meta}</p></div><span className={`status-pill ${colors[tone]}`}>{status}</span></div>; }
function Quote({name,amount,rating}:{name:string;amount:string;rating:string}) { return <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#eaf3ff] font-black text-[#0b68ed]">{name[0]}</div><div><div className="text-sm font-extrabold">{name}</div><div className="mt-1 flex items-center gap-1 text-xs text-[#69768d]"><Star size={12} fill="#ffc11a" className="text-[#ffc11a]"/>{rating}</div></div></div><div className="text-sm font-black">{amount}</div></div>; }
