import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getStripeClient } from "@/lib/stripe";
import { lookupPrice } from "@/lib/plans";

const bodySchema=z.union([z.object({kind:z.literal("subscription"),priceId:z.string().min(8)}),z.object({kind:z.literal("tokens"),tokens:z.union([z.literal(10),z.literal(20),z.literal(50)])})]);
const siteUrl=(request:Request)=>{const requestOrigin=new URL(request.url).origin;const configured=process.env.NEXT_PUBLIC_SITE_URL?.trim();if(!configured)return requestOrigin;try{const url=new URL(configured);const local=["localhost","127.0.0.1","::1"].includes(url.hostname);return process.env.VERCEL_ENV==="production"&&local?requestOrigin:url.origin}catch{return requestOrigin}};

export async function POST(request:Request){try{const body=bodySchema.parse(await request.json());const supabase=await createClient();const{data,error}=await supabase.auth.getClaims();const userId=data?.claims?.sub;const email=data?.claims?.email;if(error||typeof userId!=="string")return NextResponse.json({error:"Please log in before checking out."},{status:401});const{data:subscription}=await supabase.from("subscriptions").select("stripe_customer_id").eq("user_id",userId).maybeSingle();const stripe=getStripeClient();const checkoutOrigin=siteUrl(request);const common={customer:subscription?.stripe_customer_id||undefined,customer_email:subscription?.stripe_customer_id?undefined:typeof email==="string"?email:undefined,client_reference_id:userId,success_url:`${checkoutOrigin}/pricing?checkout=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${checkoutOrigin}/pricing?checkout=cancelled`,integration_identifier:"tradeseekerz_xqplmbar",metadata:{user_id:userId}};
if(body.kind==="subscription"){const configured=lookupPrice(body.priceId);if(!configured||configured.kind!=="subscription")return NextResponse.json({error:"That membership is not configured."},{status:400});const session=await stripe.checkout.sessions.create({...common,mode:"subscription",line_items:[{price:body.priceId,quantity:1}],allow_promotion_codes:true,billing_address_collection:"required",subscription_data:{metadata:{user_id:userId,plan_id:configured.plan.id,tokens:String(configured.tokens)}}},{idempotencyKey:`subscription:${userId}:${body.priceId}:${Math.floor(Date.now()/30000)}`});return NextResponse.json({url:session.url});}
const amount=body.tokens*100;const session=await stripe.checkout.sessions.create({...common,mode:"payment",line_items:[{quantity:1,price_data:{currency:"nzd",unit_amount:amount,product_data:{name:`${body.tokens} Trade Seekerz credits`,description:"Credits to connect with matching homeowner projects"}}}],metadata:{user_id:userId,tokens:String(body.tokens),purchase_type:"credit_top_up"}},{idempotencyKey:`tokens:${userId}:${body.tokens}:${Math.floor(Date.now()/30000)}`});return NextResponse.json({url:session.url});}catch(error){console.error("Stripe checkout error",error);return NextResponse.json({error:error instanceof Error?error.message:"Checkout could not be created."},{status:400})}}
